### ISSUE TITLE
Add the shop to the website

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#104]
2 options 
- simply add the link: https://alephium.myspreadshop.ch/
We need to agree where to add it. 
- Embed the shop directly to the website ![image](https://user-images.githubusercontent.com/52083111/201425098-389c4dcf-be7c-46ec-b1f0-2708cd108523.png)

@mvaivre @nop33 do you have a preference? Is the second option a lot of work ?

**Comment by mvaivre** [comment]
I'd add the link. I've never seen any other project embedding their shop like this. If you know any I'm curious to see the result.
Also, I'd prefer not to execute external js script in our website (security concerns).

**Comment by nop33** [comment]
I totally agree with @mvaivre.

Here are some placements, which one do you prefer?

### 1. Main navigation menu with icon

<details><summary>Click to see screenshots</summary>
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1579899/201607168-a5c6363d-c566-4840-abb9-404f3b0ab5a1.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/1579899/201607267-64eca745-fb6b-4fc6-a38a-f46f0fd2223c.png">
</details>

### 2. Main navigation menu without icon

<details><summary>Click to see screenshots</summary>
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/1579899/201607492-471aa267-5f4d-471a-b4fb-2d3774fff46b.png">

<img width="494" alt="image" src="https://user-images.githubusercontent.com/1579899/201607524-b6a8e07b-57c1-4ec8-a9e0-d9a7f8a932fa.png">
</details>

**Comment by mvaivre** [comment]
Thanks @nop33 ! 
I'd say: without the icon, but in third position (Wiki, Explorer, Shop, DL wallet, Github). 

Let's also add the link in the footer. I'm not sure where though, it doesn't really fit in the existing columns.

<details>
<summary>Stupid proposition</summary>
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/6715943/201612309-048ea218-09f5-4abf-9cd6-be24530b0a22.png">
</details>

If we wanna more visibility, I could "speed-design" & implement a "Get our merch" section just before the follow us section.

WDYT @Sakrecoer @MaudSimon ?

**Comment by MaudSimon** [comment]
Agree with Mika for the header (if we decide to put it in the header, Flux doesn't but Nym does). 
I'm not 100% sure we need it to be that visible. Maybe just a line "**Get your Alephium swag: link.** " under the Follow us section logos would be sufficient. 
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/52083111/201622221-749261d8-83be-4010-bda2-3c81fd9c892e.png">

And then we forget about the footer for now? (Flux and Nym don't have it there) 




Maybe the easy way is to just add it to the header (super useful feedback I know ^^)

**Comment by mvaivre** [comment]
FYI: we discussed with Maud and we'll:

- NOT add the shop link in the header nav nor in the footer
- I'll quickly design and implement a little section shown just above the "follow us"

**Comment by mvaivre** [comment]
Implementation done, along with global tweaks and improvements. #106
