### ISSUE TITLE
Add Ergo, Dappnode and Hodling to the list of partners

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/www#110]
As the title suggests :) Add Ergo, Dappnode and Hodling to the "Parnters" block in the ["Ecosystem" section](https://alephium.org/#ecosystem)

**Comment by Sakrecoer** [comment]
Links to add:

- `[Crypto Valley Association](https://cryptovalley.swiss/)`
- `[Dappnode](https://dappnode.io)`
- `[Ergo](https://ergoplatform.org/)`
- `[Hodling SA](https://www.hodling.ch/)`

Logos:
- Hodling SA logo for dark background: https://hodling.ch/assets/img/hodling-logo-bw-dark4Background.svg (has a color, looks like monochrome is needed. Will fix ASAP)
- ...

**Comment by nop33** [comment]
It's actually pretty straight forward to add it if you have time :) 

https://github.com/alephium/www/blob/master/src/content/homepage.md?plain=1#L96-L148

**Comment by nop33** [comment]
Ah sorry, I missed the PR, good job!
