### ISSUE TITLE
Update Roadmap

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#124]
Update Roadmap in line with https://docs.google.com/document/d/1RMZw_LTr2RBQbmCoQQ8V8eWMysAa8zJi0-UFGIBrNzk/edit?usp=sharing

Let me know if you need anything else.

When completed on the website, I'll update in docs.alephium.org.

**Comment by mvaivre** [comment]
On it.

**Comment by MaudSimon** [comment]
@mvaivre I made a suggestion in the doc to shorten the milestones list. Can you have a look and let me know if it's sufficient

**Comment by mvaivre** [comment]
Thanks @MaudSimon 🙏 I believe that this should be enough. _Updating now..._

**Comment by mvaivre** [comment]
Done and deployed to www2.alephium.org. What do you all think? 🤔 
It's still quite long TBH. We could think about having a "show details" toggle, allowing us to put the focus on primary items by default (TBD) while giving the chance to see the whole list for those interested.

**Comment by MaudSimon** [comment]
It's better. I don't think I can remove a lot more items on the milestone side but I can try if needed. I could work on shortening the roadmap items. Honestly, I think that without redesigning the section or removing too much info we won't get a much better result. I'd say we can live with this for now?
