### ISSUE TITLE
Remove/Update the Community Projects section from the website?

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#130]
The community project section of our website is outdated. Keeping in mind that we will eventually/soon re-work the website almost entirely, I think we may need to either update or delete/remove the section because it's not really a good representation of community projects as it stands right now.
The cons of updating is that it will keep being outdated and we might not want to maintain it until the re-work. And we need to agree on what we put there (happy to make a proposal if this is the road we agree on). 

Wdyt @mvaivre @VDAODAO @polarker ?

**Comment by VDAODAO** [comment]
@MaudSimon I agree we could simply remove until we redo the website. 

Other option is to keep it and say "join us on discord to see community-started projects, find a cofounder or start your own" or something along those lines and then link to discord/grants program/ambassador program.

**Comment by polarker** [comment]
Yep, sounds great to me to remove it temporarily

**Comment by MaudSimon** [comment]
@mvaivre @nop33 Can I leave this with you? Do you need me to do something?

**Comment by nop33** [comment]
If maintaining [this simple list of community projects](https://github.com/alephium/www/blob/master/src/content/homepage.md?plain=1#L148-L163) is too much work, we could indeed remove the section. Why not give the task of keeping this list up to date to Jean, who's very involved in the community?

Just to clarify, we are talking about this, right?

![image](https://github.com/alephium/www/assets/1579899/70de6873-d3d8-4ac0-80d7-27bdea9a348c)

**Comment by mvaivre** [comment]
Yeah, I agree with @nop33 thought. It's a matter of like - 1 min - to come and update the community projects list. Jean is indeed a good candidate.

**Comment by MaudSimon** [comment]
@nop33 yes we are talking about this. I would be the one with the better view on the community projects as I'm involved in discussions with them (via the grant program and etc). 
As I mentioned above, I don't mind providing a list but we'd need to agree on what criterias a project need to fulfill to appear on that list as they have for sure evolved since the list was first created. Right now, some of the projects listed aren't really community projects (pre-existing/established mining pools etc.) 

I don't mind doing it if we feel it is worth spending the time.

**Comment by MaudSimon** [comment]
If we are strict in the definition of a community project the list would be: 
- Sezame Wallet
- metapool 
- Sahhar Wallet

If we include projects that are not yet live but are in the works we can add: 
- Xoxo (go live date unclear)
- Ayin (website not live yet)

And that's pretty much it.

**Comment by nop33** [comment]
Great, thanks for this @MaudSimon! I think we could include all of the aforementioned projects.

**Comment by MaudSimon** [comment]
Are the icon clickable ? If so I'll provide links for all.

**Comment by MaudSimon** [comment]
Thinking about the best link to provide for the Sahhar wallet. 
I'm thinking we could add an additional box that says "& more" that links to https://github.com/alephium/awesome-alephium as there are a lot of community contributions that are not really projects that are still nice to indirectly showcase. What do you think?

**Comment by MaudSimon** [comment]
Here is the link for Sahhar Wallet: https://play.google.com/store/apps/details?id=com.sahhar.sahhar_wallet&pli=1

**Comment by MaudSimon** [comment]
For Xoxo & Ayin, let's wait a bit. We have a call with the first next week and the website of the second will arrive soon.

**Comment by nop33** [comment]
Even though awesome-alephium includes more things than community projects, linking to awesome-alephium might not be a bad idea!

**Comment by MaudSimon** [comment]
@nop33 Do you still need anything from my side ?

**Comment by nop33** [comment]
Sorry, I didn't get that I was to add those projects, I'll take care of it.

**Comment by MaudSimon** [comment]
We need to replace what is currently there with these 3 projects and update the link for Sahhar wallet + maybe add the link to the awesome Alephium repo. 

Thank you so much!
