### ISSUE TITLE
Updates Website

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#163]
Here is a list of things to update / add on the website

###Update "Some Numbers" Section

- Remove the number or shards + Circulating supply 
- Add the number of active addresses: https://alph-richlist.vercel.app/ displays so I think we have an endpoint for this @tdroxler ? 
- Add the TVL:  ideally directly from DeFillama : https://defillama.com/chain/Alephium (make sure stacking is included) + https://defillama.com/bridged/Alephium , otherwise maybe we have to replicate the code https://github.com/DefiLlama/DefiLlama-Adapters/tree/main/projects/alephium-bridge and  https://github.com/DefiLlama/DefiLlama-Adapters/blob/main/projects/alephium-bridge/index.js
- We could add "more" and link to the explorer

### Add Exchanges 

After investigation, most projects of similar size as us have the list of available trading venue on their website: https://docs.google.com/spreadsheets/d/11yL5WPnNZtQrQxgqVYUlefsqIHeBf7zZwjuTlRvLMKI/edit#gid=0

They either list them all or link to Coingecko. Given that it might be a challenge to keep it up to date it might be best to go with the Coingecko approach. 

I'd suggest to add an Exchange section in the Essentials tab that redirects to our Coingecko page https://www.coingecko.com/en/coins/alephium

Ideally, we should highlight our native dexes (AYIN) but not sure how to do that in a lightweight way. 

@mvaivre can I leave this with you ?

**Comment by tdroxler** [comment]
>Add the number of active addresses: https://alph-richlist.vercel.app/ displays so I think we have an endpoint for this @tdroxler ?

No we don't alph-richlist is having it's own backend

**Comment by mvaivre** [comment]
Update: 
- the guy from the richest would need to allow us to use his data (and adapt the CORS config).
- I have added the list of exchanges that I fetch from Coingecko directly
- I'm working on adding TVL and bridged amount

**Comment by MaudSimon** [comment]
@mvaivre I'll ask CGI for the actuve address data. But wouldn't it be better/more reliable that we build/use our own endpoint for data that will be on the website ?

**Comment by mvaivre** [comment]
Thomas is on it. In the meantime, please check the update live on www.alephium.org

Changes:

- More complete nav,
- Exchanges (pretty)
- TVL stats
