### ISSUE TITLE
Integrate section for partners

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/www#25]
Since we entered the UTXO Alliance and Bitcoin Association Switzerland, we need a new section for partnership. 
Typically it would include the logotype of the partner linking to their website and eventually a short description of said partner.

I'd be willing to make a mock-up if needed. 

UTXO logo: https://drive.google.com/file/d/1lf_uf0a4JuzyK49PcxNsQCMAiyDokG8R/view?usp=sharing
BAS logo: https://images.squarespace-cdn.com/content/v1/5895d62d2994ca86b0cd9807/1486226923132-GES7LLNU167XSPW77W83/image-asset.png?format=300w

**Comment by nop33** [comment]
I am curious as to where we should place such section. Anywhere between _Technology_ and _Usability_ would break the flow of information... Between _Usability_ and _Start now_ maybe? Or otherwise above _Technology_?

**Comment by Sakrecoer** [comment]
@nop33 i was thinking between _Start Now_ and _Follow Us_ but maybe that's too far hidden? It's a kinda cool memberships really... Let me think a little about it :)

**Comment by nop33** [comment]
This is probably too "extreme", since we only have 2 partners atm, but I like this idea:

![image](https://user-images.githubusercontent.com/1579899/143409837-62e41299-991b-4047-89f1-a7c33c56762a.png)

https://about.codecov.io/

**Comment by Sakrecoer** [comment]
That's beautiful, but yeah, totally overkill for 2 partners. sorry i haven't been able to allocate time for this yet. But it shouldn't require too much for now with the 2 we have, i'm planning to have it done tomorrow.

**Comment by Sakrecoer** [comment]
**Some mockups**
Following the... ehm.. following-section :sweat_smile: If it's placed before the follow-section, we might need to render the follow-section on a light-grey background to follow the rhythm
![image](https://user-images.githubusercontent.com/3484593/144070336-173fc4fe-3cb9-43c9-8b39-b29af892c35a.png)

**Dark style**
Not sure how those chain-links would look in the page. But i find it a better way to represent partnership than the classic "shaking hands". Especially in our context. I welcome all ideas :) 
![image](https://user-images.githubusercontent.com/3484593/144070490-fce17fe8-0bf7-492d-908a-70033ff94ba5.png)

**Comment by MaudSimon** [comment]
I was more thinking about adding the logos to the footer and that's it. Clicking on the logos would redirect to the partner's website

**Comment by nop33** [comment]
I'll work on adding the light version, if @mvaivre has no issue with it.

@Sakrecoer Thanks for your mockups!

**Comment by Sakrecoer** [comment]
@nop33 Thanks, though hold up a second. Seems it's "membership" not "partners" and @MaudSimon asked that we just add them in the footer bellow the Alephium logo for now.

**Comment by nop33** [comment]
hm, ok, I wait.

**Comment by mvaivre** [comment]
In the footer seems to be a good option for now, as those are not partners per se. We'll think about a dedicated section once we have more concrete partnerships to share. 

In term of design, it would be great to have both logos in white. @Sakrecoer do you think you can recolor them? :) Don't hesitate to ping me if you think I can help. Cheers!

**Comment by nop33** [comment]
I found the Bitcoin Swiss logos here: https://github.com/lclc/bitcoin-association-switzerland/tree/master/logo

**Comment by Sakrecoer** [comment]
It's not very good practice to alter the colors of corporate logo at willl... In the case of BAS, the snow would become black, unless we alter the design. but ok... :sweat_smile:  [Here they are](https://drive.google.com/drive/folders/1qSp3CY2Y1Qbll9drU0SbGo6d91ghsq5e?usp=sharing)

**Comment by Sakrecoer** [comment]
@nop33 As for the layout, unless @mvaivre has a better idea, i would go simple AF:

Bellow the Alephium logo, write "Memberships" and under that, i'd stack the logos on top of each other. (column is probably too narrow to have them on the same line?)

**Comment by nop33** [comment]
I'll give it a go and see how it looks like!
