### ISSUE TITLE
Upgrade Gatsby version from 3 to 4

### ISSUE THREAD

**Issue by nop33** [alephium/www#27]
In the [migration notes](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#minimal-nodejs-version-14150) I read that the minimal Node.js version 14.15.0. Currently we [support >=12](https://github.com/alephium/new-www/blob/main/package.json#L11). Is there any problem with dropping support for 12 so that we can stay up to date with Gatsby's new improvements and features?

**Comment by polarker** [comment]
@nop33 sure, as it's a standalone website, we could definitely relax our practice here
