### ISSUE TITLE
Add Team Modal in the Footer

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#48]
In the footer in the current "Company" Section, add a Team under the About.
Content for the modal can be found on slide 12 of our slide deck. Link sent on Slack.

Please note, we will likely add more people in the future.

**Comment by nop33** [comment]
Will do!

**Comment by nop33** [comment]
@MaudSimon here's a preview: https://www2.alephium.org/

**Comment by MaudSimon** [comment]
Looks great! Thank you :)
