### ISSUE TITLE
Avoid displaying scrollbars too close to modal's content

### ISSUE THREAD

**Issue by mvaivre** [alephium/www#52]
This is an issue especially on OSes with solid scrollbars (see screenshot below from windows). 
We should probably play with padding/margin to keep the scrollbars along the side of the modal window.

![image](https://user-images.githubusercontent.com/6715943/145012039-d6f918a6-8912-4be5-bbfe-4187f50ad53e.png)

**Comment by nop33** [comment]
Good point @mvaivre, I'll have a look into it.
