### ISSUE TITLE
Add Vladimir to the team page 

### ISSUE THREAD

**Issue by MaudSimon** [alephium/www#56]
Name : Vladimir Moshnyager

Title: Marketing & Project Awareness 

Pic : https://drive.google.com/file/d/17DMWwmQv6hslKjr132-BiD8j3f_RKOqA/view?usp=sharing

**Comment by MaudSimon** [comment]
Not urgent.

**Comment by MaudSimon** [comment]
@nop33 when do you think you'll have time to quickly make the addition? Is there a way for me to do it myself without breaking everything ?

**Comment by nop33** [comment]
I'm so sorry @MaudSimon , this task completely went past me. I need to figure out how to use GitHub's interface better. I've made the required change and deployed a preview here: [www2.alephium.org](https://www2.alephium.org/). If everything is ok, I can deploy in production.

**Comment by MaudSimon** [comment]
No problem at all! It wasn't urgent. Even now, it's not critical but nice to have before an afflux of new people :)

**Comment by MaudSimon** [comment]
Looks good to me :)
