### ISSUE TITLE
links to community channels

### ISSUE THREAD

**Issue by ferdinandhodl** [alephium/www#71]
can we put the links to the community channels

- [Chinese discord](https://discord.com/channels/747741246667227157/908043080773566474)
- [French discord](https://discord.com/channels/747741246667227157/908086349641445436)
- [German discord](https://discord.com/channels/747741246667227157/908086677245919252)
- [Russian discord](https://discord.com/channels/747741246667227157/910086877724438528)
- [Czech discord](https://discord.com/channels/747741246667227157/926505567458050098)
- [Spanish discord](https://discord.com/channels/747741246667227157/9294760459487314320)
- [Turkish discord](https://discord.com/channels/747741246667227157/932275739028496434)
- [Arab discord](https://discord.com/channels/747741246667227157/938131961866776646)
- [Alephium Group TG](https://t.me/alephiumgroup)
- [Portuguese TG](https://t.me/Alephium_pt)
- [Vietnamese TG](https://t.me/alephiumvn)
- [Indonesian TG](https://t.me/AlephiumID)
- [Russian TG](https://t.me/alephiumgroup_ru)
- [Trading TG](https://t.me/alephium_trading)
- [Mining TG](https://t.me/alephium_mining)

to the official website?

**Comment by lf94** [comment]
@MaudSimon not sure how you'd want to handle a request like this?

**Comment by MaudSimon** [comment]
@ferdinandhodl On the website, we will only link the official (team managed) channels. 
@Sakrecoer we can definitely add the community managed channel to Awesome Alephium. Could you take care of that if you think it's relevant, feel free to suggest a better location if you see one.

**Comment by Sakrecoer** [comment]
Thank you @ferdinandhodl ! :raised_hands: 

We have this list on the wiki: https://wiki.alephium.org/5min-overview#non-official-content--communities

But i see that you are completing it, which is very nice and appreciated! I will amend the list accordingly!

**Comment by Sakrecoer** [comment]
Closing this issue here to continue it at https://github.com/alephium/wiki/issues/32
