### ISSUE TITLE
Add Herominer and EnigmaPool to Ecosystem section

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/www#73]
Not sure which branch is the test branch for the website... Pasting the required content for the changes here.

Content required in https://github.com/alephium/www/blob/master/src/content/homepage.md :

```
        - title: 'Herominer'
          logo: '../images/logos/hero-miner-bw.png'
          url: https://herominers.com/
        - title: EnigmaPool
          logo: ''
          url: https://enigmapool.com/
```
Black'n'white herominer logo:

![hero-miner-bw](https://user-images.githubusercontent.com/3484593/155979937-aaf00da1-849e-4439-bd7c-021757522d0f.png)

(EnigamPool doesn't seem to have a logo at the time of writing)

**Comment by nop33** [comment]
> Not sure which branch is the test branch for the website

Any branch can be deployed to www2.alephium.org.

Thanks for the diff, I'll add it now.

**Comment by Sakrecoer** [comment]
Thank you very much @nop33 !  How do we define which branch is displayed on `www2`? 

Please note i haven't uploaded the logo-image to it's location yet.

**Comment by nop33** [comment]
1. Create a new branch and make your changes
2. Go to the GitHub Actions page: https://github.com/alephium/www/actions
3. Click on "Publish to Test" on the left hand side menu: https://github.com/alephium/www/actions/workflows/publish_to_test.yaml
4. Click "Run workflow" on the right side
5. Select your branch with the changes
6. Click the green button "Run workflow"

**Comment by nop33** [comment]
I already followed the above procedure, here's the preview: https://www2.alephium.org

**Comment by Sakrecoer** [comment]
Seems the link checker got unlucky and failed on metapool.tech/dashboard. Unlucky because the link seems fine from here...

**Comment by nop33** [comment]
I did some tests and everything seems to be fine with metapool. I don't understand why we get this false negative result. For now I just whitelisted metapool, but if this keeps happening maybe we need to find a better solution for a link checking tool...
