### ISSUE TITLE
v1.5

### ISSUE THREAD

**Issue by lf94** [alephium/www#81]
Design: https://www.figma.com/file/6tujIX9FtkIAUSjYycJUHi/Alephium---Website-ecosystem?node-id=0%3A1
Content: https://github.com/AlephiumFoundation/Website/issues/10#issuecomment-1065025098

Notes:
* Omit the usability section
* Static design for this iteration (no parallax, no confetti)

**Comment by lf94** [comment]
@mvaivre Am I removing the Numbers, Start Now, and Follow Us sections?

**Comment by mvaivre** [comment]
As said [on Slack](https://alephium.slack.com/archives/C035XRG5UBC/p1652111294077319?thread_ts=1652110179.139879&cid=C035XRG5UBC), we don't keep the "Start Now" section, but we keep the Follow Us section, using the dark theme.

Numbers, I seem to remember that we keep it, but we wanted to swap the numbers for some others, more aligned with the current state of the project. @MaudSimon, do you remember? The [brainstorm doc](https://docs.google.com/document/d/1URZ9kb5EQZXEymy-vYiSb0gnsA8oFxEPoFr-assauUA/edit) says: "We’d like to add the numbers that will be in the new explorer + more : Hashrate, Circulating supply, Transactions (per day ?), Blocks, number of chains, price + more". Any update on that topic Maud?

**Comment by lf94** [comment]
For the milestones timelines, did we want to construct it as:

* An SVG
* Canvas drawing
* HTML & CSS trickery

**Comment by mvaivre** [comment]
I'd say, HTML & CSS trickery :)

**Comment by MaudSimon** [comment]
@mvaivre: number of wallets (not sure have something but Sven does), supply (like on the explorer), transactions, hashrate, number of shards. 

Is it possible to have those updated daily (except the number of shards) ?

Sorry for brevity, running around!

**Comment by lf94** [comment]
I don't think the explorer can report the number of wallets yet; we can do everything else though. Instead of daily the website can request the numbers from the explorer when the page loads? @mvaivre ?

**Comment by MaudSimon** [comment]
Might be worth checking with Sven (cgi/bin on Discord) how he got the number, he might have a public endpoint we could leverage (if we feel comfortable doing so). 
I leave it up to you, if we can't find a way to display the wallet number you guys feel comfortable with, I guess we'll do without :)

**Comment by lf94** [comment]
I'll leave the wallet number out for now; I'd like to be able to easily pull this value from the explorer.

**Comment by lf94** [comment]
@mvaivre any ideas on how we're getting to the separated technology page?

**Comment by lf94** [comment]
@mvaivre on non-webkit browsers, the text gradient is going to look like this:

![1652714064](https://user-images.githubusercontent.com/547923/168625952-339e9ce3-9a80-418d-90fb-ea874501269c.png)

Did we want something alternative?

Edit: If I use `webkit-linear-gradient` it'll be ignored and should just show regular white text on the black background.

**Comment by mvaivre** [comment]
@lf94 Let's use plain blue text as a fallback :) A color value from the middle of the gradient will do it.

**Comment by lf94** [comment]
Sounds good! How do you detect the failure of the gradient in this case?...

**Comment by mvaivre** [comment]
[This](https://fossheim.io/writing/posts/css-text-gradient/) shows how to set a fallback.

**Comment by lf94** [comment]
Ah! Right, the gradient is a background anyway. Thanks :)

**Comment by lf94** [comment]
That fallback is for backgrounds, not text color?

**Comment by lf94** [comment]
If we only target webkit, blink or gecko engines we'll be ok - no fallback needed.

**Comment by lf94** [comment]
For the record: The technology section is going to be a separate page, with the tip boxes and links removed.

**Comment by mvaivre** [comment]
Just to be clear: the [new content](https://docs.google.com/document/d/1l-POvqul5x6phDL5UjEWSl3RJjLdFpRYvgJ0uRnyALI/edit#heading=h.3qk46muwgbm5) is to stay on the homepage, with the tip boxes and links removed. 
The old technology content will be in a dedicated separate page, with the tip boxes and links *not* removed.

**Comment by lf94** [comment]
Oh, thanks for that! Will both pages still have the numbers sections on them? Technically they are part of the technology section...

**Comment by mvaivre** [comment]
No, the numbers are only for the homepage :)

**Comment by nop33** [comment]
I believe this issue can now be closed.
