### ISSUE TITLE
Wishlist: deep links to sections (`#sectionname`)

### ISSUE THREAD

**Issue by Sakrecoer** [alephium/www#90]
Dear Santa,

The other day i shared the roadmap from our wiki because it deep-links (`#milestones--roadmap`), i found myself wishing i could deep-link to the moar beautiful roadmap on the website in the same way. 

Is this something that we can have?

**Comment by nop33** [comment]
Yes, you can get it for Christmas 🎄 

😆

**Comment by nop33** [comment]
@Sakrecoer  I programmatically added anchors to all section titles.

Here's an example (make sure to hard-refresh): https://www2.alephium.org/#what's_next

You can find the ID of each section by inspecting the header element of each section:

![image](https://user-images.githubusercontent.com/1579899/185881250-aae76ee9-db73-416e-8f60-99955b694750.png)

**Comment by Sakrecoer** [comment]
A-MA-ZING! Exactly what i was looking for! :tada: Thank you for your swift response and reaction @nop33  !!
